#!/usr/bin/env sh

BASEDIR=$(dirname $0)

TARGETDIR=""
if [ ! -z "$1" ]; then
  TARGETDIR=$1
else
  TARGETDIR="$BASEDIR/output"
fi

cd $BASEDIR

code/lib/py-init
. code/lib/python/bin/activate

peru sync

find "$TARGETDIR/" -mindepth 1 -delete
cp -r code/stylesheets/ $TARGETDIR/stylesheets
cp -r code/javascripts/ $TARGETDIR/javascripts

nim c -r code/generate.nim ./snippets/ $TARGETDIR
