#!/usr/bin/env sh

BASEDIR=$(dirname $0)

cd $BASEDIR

code/lib/py-init
. code/lib/python/bin/activate

peru sync

mkdir output
cp -R code/stylesheets/ output/stylesheets
cp -R code/javascripts/ output/javascripts

nim c -r code/generate.nim ./snippets/ ./output/
