#!/usr/bin/env sh

BASEDIR=$(dirname $0)

mkdir "$BASEDIR/python"

virtualenv --python=python3 "$BASEDIR/python/"
source "$BASEDIR/python/bin/activate"

requirements=$(mktemp)
trap "rm $requirements" EXIT

tee $requirements <<-EOF >/dev/null
  PyYAML==3.11
  Pygments==2.0.1
  asyncio==3.4.1
  docopt==0.6.2
  pathlib==1.0.1
  peru==0.1.1
EOF

pip install -r $requirements
